# Generated by Django 5.2.3 on 2025-06-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('administrador', 'Administrador')], default='cliente', help_text='Rol del usuario en el sistema', max_length=20),
        ),
    ]
