# Generated by Django 5.2.3 on 2025-06-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_cliente_rol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="rol",
        ),
    ]
