# Generated by Django 5.2.5 on 2026-01-26 20:32

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_remove_cliente_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuraciontienda",
            name="sobre_nosotros",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="sku",
            field=models.CharField(
                default=post.models.generar_sku,
                editable=False,
                max_length=50,
                unique=True,
            ),
        ),
    ]
