# Generated by Django 5.2.3 on 2025-06-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_remove_cliente_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="porcentaje_recompensa",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Porcentaje de recompensa para este producto (ej. 0.10 para 10%).",
                max_digits=5,
                null=True,
            ),
        ),
    ]
