# Generated by Django 5.2.5 on 2026-01-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_configuraciontienda_sobre_nosotros_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuraciontienda",
            name="dias_validez_cupon_recompensa",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Días de validez del cupón de recompensa desde su generación.",
            ),
        ),
        migrations.AddField(
            model_name="configuraciontienda",
            name="max_valor_recompensa_pedido",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Valor máximo del cupón de recompensa.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="configuraciontienda",
            name="min_valor_recompensa_pedido",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Valor mínimo del cupón de recompensa.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="configuraciontienda",
            name="porcentaje_recompensa_pedido",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Porcentaje del subtotal del pedido para el cupón de recompensa.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="configuraciontienda",
            name="valor_fijo_recompensa_pedido",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Si es mayor que 0, se usará este valor fijo en lugar del porcentaje.",
                max_digits=12,
            ),
        ),
    ]
