# Generated by Django 5.2.5 on 2026-01-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_configuraciontienda_dias_validez_cupon_recompensa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resena",
            name="aprobado",
            field=models.BooleanField(default=True),
        ),
    ]
